Check for existence of attribute _grpc_server (#617)
Without this check, this method fails with:

Exception ignored in: <bound method GRPCDataset.__del__ of <GRPCDataset shapes: (2,), types: tf.int16>>
Traceback (most recent call last):
  File .../lib/python3.6/site-packages/tensorflow_io/grpc/python/ops/grpc_ops.py, line 59, in __del__
    if self._grpc_server is not None:
AttributeError: 'GRPCDataset' object has no attribute '_grpc_server'

when instantiating GRPCDataset with the normal constructor instead of from_numpy.